import type { AIFutureResilienceProfile, Major } from "@/lib/types";

function aiProfile(
  aiReason: string,
  values: Omit<AIFutureResilienceProfile, "aiReason">
): AIFutureResilienceProfile {
  return { aiReason, ...values };
}

const techBuilder = aiProfile(
  "pekerjaan teknologi akan banyak memakai AI sebagai alat bantu, tetapi tetap membutuhkan problem solving, desain sistem, keamanan, dan pemahaman kebutuhan manusia.",
  {
    humanInteraction: 56,
    creativity: 68,
    physicalPractical: 25,
    ethicalJudgment: 70,
    complexProblemSolving: 88,
    professionalAccountability: 72,
    aiAugmentationPotential: 94,
    industryGrowth: 92,
    nonRoutineWork: 74
  }
);

const dataBuilder = aiProfile(
  "AI bisa mempercepat analisis rutin, namun interpretasi data, keputusan bisnis, etika, dan komunikasi insight tetap sangat penting.",
  {
    humanInteraction: 50,
    creativity: 60,
    physicalPractical: 18,
    ethicalJudgment: 74,
    complexProblemSolving: 86,
    professionalAccountability: 70,
    aiAugmentationPotential: 96,
    industryGrowth: 91,
    nonRoutineWork: 68
  }
);

const healthBuilder = aiProfile(
  "bidang kesehatan kuat karena membutuhkan empati, tanggung jawab profesional, penilaian etis, dan kontak langsung dengan manusia.",
  {
    humanInteraction: 94,
    creativity: 45,
    physicalPractical: 86,
    ethicalJudgment: 95,
    complexProblemSolving: 82,
    professionalAccountability: 96,
    aiAugmentationPotential: 76,
    industryGrowth: 86,
    nonRoutineWork: 84
  }
);

const creativeBuilder = aiProfile(
  "AI dapat membantu produksi ide dan aset, tetapi arah kreatif, rasa, strategi komunikasi, dan pemahaman audiens tetap menjadi kekuatan manusia.",
  {
    humanInteraction: 66,
    creativity: 94,
    physicalPractical: 42,
    ethicalJudgment: 62,
    complexProblemSolving: 70,
    professionalAccountability: 58,
    aiAugmentationPotential: 90,
    industryGrowth: 75,
    nonRoutineWork: 78
  }
);

const socialBuilder = aiProfile(
  "pekerjaan ini bertumpu pada komunikasi, empati, konteks sosial, dan judgement manusia sehingga AI lebih cocok menjadi alat bantu kerja.",
  {
    humanInteraction: 90,
    creativity: 66,
    physicalPractical: 35,
    ethicalJudgment: 88,
    complexProblemSolving: 76,
    professionalAccountability: 82,
    aiAugmentationPotential: 70,
    industryGrowth: 74,
    nonRoutineWork: 80
  }
);

const businessBuilder = aiProfile(
  "tugas administrasi bisa dibantu AI, tetapi strategi, negosiasi, leadership, dan pemahaman pasar tetap sulit digantikan penuh.",
  {
    humanInteraction: 78,
    creativity: 70,
    physicalPractical: 24,
    ethicalJudgment: 68,
    complexProblemSolving: 76,
    professionalAccountability: 70,
    aiAugmentationPotential: 86,
    industryGrowth: 80,
    nonRoutineWork: 70
  }
);

const engineeringBuilder = aiProfile(
  "pekerjaan teknik menggabungkan perhitungan, praktik lapangan, keselamatan, dan tanggung jawab profesional; AI membantu desain dan simulasi.",
  {
    humanInteraction: 58,
    creativity: 64,
    physicalPractical: 88,
    ethicalJudgment: 78,
    complexProblemSolving: 86,
    professionalAccountability: 90,
    aiAugmentationPotential: 78,
    industryGrowth: 82,
    nonRoutineWork: 86
  }
);

const lawBuilder = aiProfile(
  "riset hukum dapat dibantu AI, tetapi interpretasi, etika, advokasi, negosiasi, dan tanggung jawab profesional tetap membutuhkan manusia.",
  {
    humanInteraction: 82,
    creativity: 56,
    physicalPractical: 18,
    ethicalJudgment: 96,
    complexProblemSolving: 80,
    professionalAccountability: 94,
    aiAugmentationPotential: 78,
    industryGrowth: 70,
    nonRoutineWork: 82
  }
);

export const majors: Major[] = [
  {
    id: "informatika",
    name: "Informatika",
    cluster: "Teknologi",
    careerDirection: "Software engineering, AI product, dan pengembangan sistem digital",
    relatedCareers: ["Software Engineer", "AI Engineer", "Mobile Developer", "Cloud Engineer"],
    subjects: ["Matematika", "Komputer/TIK", "Fisika"],
    interests: ["Coding/teknologi", "Menghitung/analisis data"],
    skills: ["Logika", "Problem solving", "Teknologi", "Numerik/hitung-hitungan", "Ketelitian"],
    workStyles: ["Banyak analisis sendiri", "Terstruktur dan detail", "Kreatif dan fleksibel"],
    problemAreas: ["Teknologi", "Bisnis", "Pendidikan"],
    schoolBackgrounds: ["IPA", "SMK Teknik", "SMK Kreatif/Multimedia"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar", "Sertifikasi/bootcamp"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["algoritma dasar", "struktur data", "bahasa Inggris teknis", "portofolio proyek"],
    nextSteps: ["Bangun 2-3 proyek kecil", "Latihan logika dan matematika dasar", "Ikuti kursus pemrograman terstruktur"],
    cautionNotes: ["Persaingan masuk dan standar portofolio bisa tinggi di kampus populer."],
    aiProfile: techBuilder
  },
  {
    id: "sistem-informasi",
    name: "Sistem Informasi",
    cluster: "Teknologi & Bisnis",
    careerDirection: "Jembatan antara kebutuhan bisnis, data, dan solusi teknologi",
    relatedCareers: ["Business Analyst", "Product Manager", "System Analyst", "ERP Consultant"],
    subjects: ["Komputer/TIK", "Ekonomi", "Matematika", "Bahasa"],
    interests: ["Coding/teknologi", "Berjualan/bisnis", "Mengorganisir acara", "Menghitung/analisis data"],
    skills: ["Komunikasi", "Logika", "Problem solving", "Teknologi", "Leadership"],
    workStyles: ["Banyak bertemu orang", "Terstruktur dan detail", "Kreatif dan fleksibel"],
    problemAreas: ["Teknologi", "Bisnis", "Keuangan"],
    schoolBackgrounds: ["IPA", "IPS", "SMK Bisnis", "SMK Kreatif/Multimedia"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar", "Sertifikasi/bootcamp"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["analisis proses bisnis", "database dasar", "komunikasi stakeholder", "UX dasar"],
    nextSteps: ["Pelajari spreadsheet dan database", "Coba membuat prototype aplikasi sederhana", "Latih presentasi solusi"],
    cautionNotes: ["Perlu nyaman belajar teknologi sekaligus memahami kebutuhan orang lain."],
    aiProfile: techBuilder
  },
  {
    id: "data-science",
    name: "Data Science",
    cluster: "Data & Analitik",
    careerDirection: "Analisis data, machine learning, dan pengambilan keputusan berbasis bukti",
    relatedCareers: ["Data Analyst", "Data Scientist", "Machine Learning Engineer", "BI Analyst"],
    subjects: ["Matematika", "Komputer/TIK", "Ekonomi"],
    interests: ["Menghitung/analisis data", "Coding/teknologi"],
    skills: ["Numerik/hitung-hitungan", "Ketelitian", "Logika", "Problem solving", "Teknologi"],
    workStyles: ["Banyak analisis sendiri", "Terstruktur dan detail"],
    problemAreas: ["Teknologi", "Bisnis", "Keuangan", "Kesehatan", "Lingkungan"],
    schoolBackgrounds: ["IPA", "IPS", "SMK Teknik", "SMK Bisnis"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar", "Sertifikasi/bootcamp"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["statistika", "Python atau SQL", "visualisasi data", "cara menjelaskan insight"],
    nextSteps: ["Latihan statistik dasar", "Buat proyek analisis data publik", "Pelajari Python, SQL, dan dashboard"],
    cautionNotes: ["Butuh konsistensi belajar matematika dan membaca pola data."],
    aiProfile: dataBuilder
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    cluster: "Teknologi",
    careerDirection: "Keamanan sistem, perlindungan data, dan audit risiko digital",
    relatedCareers: ["Security Analyst", "Penetration Tester", "SOC Analyst", "Risk Engineer"],
    subjects: ["Komputer/TIK", "Matematika", "Fisika"],
    interests: ["Coding/teknologi", "Memperbaiki barang/mesin", "Menghitung/analisis data"],
    skills: ["Logika", "Ketelitian", "Problem solving", "Teknologi"],
    workStyles: ["Terstruktur dan detail", "Banyak analisis sendiri", "Praktik langsung"],
    problemAreas: ["Teknologi", "Hukum", "Keuangan"],
    schoolBackgrounds: ["IPA", "SMK Teknik", "SMK Kreatif/Multimedia"],
    pathwayTags: ["PTS bagus di kota besar", "Sertifikasi/bootcamp", "PTN di Jawa"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["jaringan komputer", "Linux dasar", "etika keamanan", "sertifikasi dasar"],
    nextSteps: ["Pelajari jaringan dasar", "Ikuti lab keamanan legal", "Buat catatan portofolio write-up"],
    cautionNotes: ["Bidang ini menuntut etika tinggi dan pembelajaran terus-menerus."],
    aiProfile: techBuilder
  },
  {
    id: "bisnis-digital",
    name: "Bisnis Digital",
    cluster: "Bisnis & Teknologi",
    careerDirection: "Pengembangan usaha, pemasaran digital, dan produk berbasis teknologi",
    relatedCareers: ["Digital Marketer", "Growth Specialist", "E-commerce Manager", "Product Associate"],
    subjects: ["Ekonomi", "Komputer/TIK", "Bahasa", "Matematika"],
    interests: ["Berjualan/bisnis", "Coding/teknologi", "Membuat desain/konten", "Menulis/berbicara"],
    skills: ["Komunikasi", "Kreativitas", "Leadership", "Teknologi", "Problem solving"],
    workStyles: ["Kreatif dan fleksibel", "Banyak bertemu orang", "Dinamis di lapangan"],
    problemAreas: ["Bisnis", "Teknologi", "Kreatif/media", "Keuangan"],
    schoolBackgrounds: ["IPS", "SMK Bisnis", "SMK Kreatif/Multimedia", "IPA"],
    pathwayTags: ["PTS bagus di kota besar", "Sertifikasi/bootcamp", "Diploma/vokasi"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["riset pasar", "konten digital", "data pemasaran", "eksperimen bisnis"],
    nextSteps: ["Coba jual produk kecil secara online", "Bangun portofolio konten atau campaign", "Pelajari analitik media sosial"],
    cautionNotes: ["Tren digital cepat berubah, jadi perlu sering eksperimen."],
    aiProfile: businessBuilder
  },
  {
    id: "psikologi",
    name: "Psikologi",
    cluster: "Sosial & Perilaku",
    careerDirection: "Memahami perilaku manusia, konseling dasar, HR, riset, dan pengembangan diri",
    relatedCareers: ["HR Specialist", "Counselor Assistant", "Research Assistant", "People Development"],
    subjects: ["Sosiologi", "Biologi", "Bahasa", "Sejarah"],
    interests: ["Membantu orang", "Menulis/berbicara", "Mengorganisir acara"],
    skills: ["Empati", "Komunikasi", "Ketelitian", "Public speaking", "Problem solving"],
    workStyles: ["Banyak bertemu orang", "Terstruktur dan detail", "Banyak analisis sendiri"],
    problemAreas: ["Sosial", "Pendidikan", "Kesehatan", "Bisnis"],
    schoolBackgrounds: ["IPA", "IPS", "Bahasa", "SMK Kesehatan"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar"],
    flexible: true,
    applied: false,
    expensive: false,
    competitive: true,
    skillGaps: ["mendengar aktif", "metode riset", "etika profesi", "statistika dasar"],
    nextSteps: ["Baca pengantar psikologi", "Latih observasi dan journaling", "Ikut kegiatan mentoring atau organisasi"],
    cautionNotes: ["Untuk menjadi psikolog profesional, perlu pendidikan lanjutan dan izin praktik."],
    aiProfile: socialBuilder
  },
  {
    id: "pendidikan",
    name: "Pendidikan",
    cluster: "Pendidikan",
    careerDirection: "Pengajaran, pengembangan belajar, teknologi pendidikan, dan pendampingan siswa",
    relatedCareers: ["Guru", "Instructional Designer", "Tutor", "Education Program Officer"],
    subjects: ["Bahasa", "Sosiologi", "Sejarah", "Matematika"],
    interests: ["Membantu orang", "Menulis/berbicara", "Mengorganisir acara"],
    skills: ["Komunikasi", "Empati", "Public speaking", "Leadership", "Kreativitas"],
    workStyles: ["Banyak bertemu orang", "Kreatif dan fleksibel", "Terstruktur dan detail"],
    problemAreas: ["Pendidikan", "Sosial"],
    schoolBackgrounds: ["IPA", "IPS", "Bahasa", "SMK Bisnis", "SMK Kreatif/Multimedia"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "Kuliah dekat rumah"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["metode mengajar", "public speaking", "desain materi", "evaluasi belajar"],
    nextSteps: ["Coba menjadi tutor sebaya", "Buat materi belajar singkat", "Observasi gaya mengajar guru favorit"],
    cautionNotes: ["Penghasilan dan jalur karier bervariasi, jadi penting membangun spesialisasi."],
    aiProfile: socialBuilder
  },
  {
    id: "keperawatan",
    name: "Keperawatan",
    cluster: "Kesehatan",
    careerDirection: "Perawatan pasien, edukasi kesehatan, dan pelayanan klinis",
    relatedCareers: ["Perawat", "Nurse Educator", "Care Coordinator", "Homecare Nurse"],
    subjects: ["Biologi", "Kimia", "Bahasa"],
    interests: ["Membantu orang", "Eksperimen/lab", "Kerja lapangan"],
    skills: ["Empati", "Ketelitian", "Komunikasi", "Kerja praktik", "Problem solving"],
    workStyles: ["Praktik langsung", "Banyak bertemu orang", "Terstruktur dan detail"],
    problemAreas: ["Kesehatan", "Sosial"],
    schoolBackgrounds: ["IPA", "SMK Kesehatan"],
    pathwayTags: ["Diploma/vokasi", "PTN luar Jawa", "Kuliah dekat rumah"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["anatomi dasar", "komunikasi pasien", "ketahanan fisik", "prosedur klinis"],
    nextSteps: ["Cari informasi program D3/S1 Keperawatan", "Latih disiplin dan empati", "Pelajari biologi manusia"],
    cautionNotes: ["Pekerjaan bisa membutuhkan shift dan kesiapan fisik."],
    aiProfile: healthBuilder
  },
  {
    id: "kesehatan-masyarakat",
    name: "Kesehatan Masyarakat",
    cluster: "Kesehatan & Sosial",
    careerDirection: "Pencegahan penyakit, edukasi kesehatan, program masyarakat, dan kebijakan kesehatan",
    relatedCareers: ["Health Promoter", "Epidemiology Assistant", "Program Officer", "K3 Officer"],
    subjects: ["Biologi", "Sosiologi", "Matematika", "Bahasa"],
    interests: ["Membantu orang", "Mengorganisir acara", "Kerja lapangan", "Menghitung/analisis data"],
    skills: ["Komunikasi", "Empati", "Leadership", "Ketelitian", "Numerik/hitung-hitungan"],
    workStyles: ["Dinamis di lapangan", "Banyak bertemu orang", "Terstruktur dan detail"],
    problemAreas: ["Kesehatan", "Sosial", "Lingkungan", "Pendidikan"],
    schoolBackgrounds: ["IPA", "IPS", "SMK Kesehatan"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "Kuliah dekat rumah"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["statistik dasar", "komunikasi publik", "riset lapangan", "manajemen program"],
    nextSteps: ["Ikut kegiatan sosial kesehatan", "Pelajari isu stunting atau kesehatan remaja", "Latih presentasi edukasi"],
    cautionNotes: ["Sering bekerja lintas pihak dan membutuhkan kemampuan koordinasi."],
    aiProfile: healthBuilder
  },
  {
    id: "bimbingan-konseling",
    name: "Bimbingan Konseling",
    cluster: "Pendidikan & Sosial",
    careerDirection: "Pendampingan siswa, konseling pendidikan, dan pengembangan potensi remaja",
    relatedCareers: ["Guru BK", "Student Counselor", "Career Counselor", "Program Mentor"],
    subjects: ["Sosiologi", "Bahasa", "Sejarah"],
    interests: ["Membantu orang", "Menulis/berbicara", "Mengorganisir acara"],
    skills: ["Empati", "Komunikasi", "Public speaking", "Leadership"],
    workStyles: ["Banyak bertemu orang", "Terstruktur dan detail"],
    problemAreas: ["Pendidikan", "Sosial"],
    schoolBackgrounds: ["IPS", "Bahasa", "IPA"],
    pathwayTags: ["PTN luar Jawa", "Kuliah dekat rumah", "PTN di Jawa"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["konseling dasar", "etika pendampingan", "asesmen minat", "komunikasi keluarga"],
    nextSteps: ["Coba jadi mentor adik kelas", "Pelajari dasar konseling remaja", "Diskusi dengan guru BK"],
    cautionNotes: ["Perlu kesabaran dan batas profesional saat mendampingi orang lain."],
    aiProfile: socialBuilder
  },
  {
    id: "dkv",
    name: "Desain Komunikasi Visual",
    cluster: "Kreatif & Media",
    careerDirection: "Desain visual, branding, ilustrasi, UI, dan komunikasi kreatif",
    relatedCareers: ["Graphic Designer", "UI Designer", "Brand Designer", "Illustrator"],
    subjects: ["Seni/Desain", "Komputer/TIK", "Bahasa"],
    interests: ["Membuat desain/konten", "Menulis/berbicara", "Coding/teknologi"],
    skills: ["Kreativitas", "Komunikasi", "Teknologi", "Ketelitian"],
    workStyles: ["Kreatif dan fleksibel", "Banyak analisis sendiri"],
    problemAreas: ["Kreatif/media", "Bisnis", "Teknologi", "Pendidikan"],
    schoolBackgrounds: ["Bahasa", "SMK Kreatif/Multimedia", "IPS", "IPA"],
    pathwayTags: ["PTS bagus di kota besar", "Diploma/vokasi", "Sertifikasi/bootcamp"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["komposisi visual", "software desain", "riset audiens", "portofolio"],
    nextSteps: ["Kumpulkan portofolio 8-12 karya", "Latih desain ulang poster atau brand lokal", "Pelajari prinsip UI/UX dasar"],
    cautionNotes: ["AI membuat produksi visual lebih cepat, jadi nilai portofolio dan konsep harus kuat."],
    aiProfile: creativeBuilder
  },
  {
    id: "animasi-multimedia",
    name: "Animasi & Multimedia",
    cluster: "Kreatif & Media",
    careerDirection: "Animasi, konten video, motion graphics, dan produksi media digital",
    relatedCareers: ["Animator", "Motion Designer", "Video Editor", "Content Producer"],
    subjects: ["Seni/Desain", "Komputer/TIK", "Bahasa"],
    interests: ["Membuat desain/konten", "Coding/teknologi"],
    skills: ["Kreativitas", "Teknologi", "Ketelitian", "Problem solving"],
    workStyles: ["Kreatif dan fleksibel", "Praktik langsung"],
    problemAreas: ["Kreatif/media", "Teknologi", "Pendidikan"],
    schoolBackgrounds: ["SMK Kreatif/Multimedia", "Bahasa", "IPA", "IPS"],
    pathwayTags: ["Diploma/vokasi", "Sertifikasi/bootcamp", "PTS bagus di kota besar"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["storytelling visual", "editing", "motion tools", "konsistensi portofolio"],
    nextSteps: ["Buat 3 video pendek", "Latih storyboard", "Pelajari software animasi pilihan"],
    cautionNotes: ["Bidang ini sangat portofolio-driven dan perlu latihan rutin."],
    aiProfile: creativeBuilder
  },
  {
    id: "komunikasi",
    name: "Ilmu Komunikasi",
    cluster: "Sosial & Media",
    careerDirection: "Public relations, media, content strategy, dan komunikasi organisasi",
    relatedCareers: ["PR Officer", "Content Strategist", "Journalist", "Social Media Specialist"],
    subjects: ["Bahasa", "Sosiologi", "Seni/Desain", "Sejarah"],
    interests: ["Menulis/berbicara", "Membuat desain/konten", "Mengorganisir acara", "Membantu orang"],
    skills: ["Komunikasi", "Public speaking", "Kreativitas", "Bahasa asing", "Leadership"],
    workStyles: ["Banyak bertemu orang", "Kreatif dan fleksibel", "Dinamis di lapangan"],
    problemAreas: ["Kreatif/media", "Sosial", "Bisnis", "Pendidikan"],
    schoolBackgrounds: ["IPS", "Bahasa", "SMK Kreatif/Multimedia", "IPA"],
    pathwayTags: ["PTN di Jawa", "PTS bagus di kota besar", "Kuliah dekat rumah"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["menulis efektif", "riset audiens", "public speaking", "strategi konten"],
    nextSteps: ["Buat portofolio tulisan atau konten", "Ikut organisasi atau event sekolah", "Latih presentasi dan wawancara"],
    cautionNotes: ["Persaingan karier tinggi, portofolio dan pengalaman organisasi sangat membantu."],
    aiProfile: socialBuilder
  },
  {
    id: "desain-produk",
    name: "Desain Produk",
    cluster: "Kreatif & Industri",
    careerDirection: "Perancangan produk, pengalaman pengguna, dan solusi benda sehari-hari",
    relatedCareers: ["Product Designer", "Industrial Designer", "UX Researcher", "Design Researcher"],
    subjects: ["Seni/Desain", "Fisika", "Komputer/TIK"],
    interests: ["Membuat desain/konten", "Memperbaiki barang/mesin", "Kerja lapangan"],
    skills: ["Kreativitas", "Problem solving", "Ketelitian", "Kerja praktik"],
    workStyles: ["Kreatif dan fleksibel", "Praktik langsung", "Banyak bertemu orang"],
    problemAreas: ["Kreatif/media", "Teknologi", "Infrastruktur", "Lingkungan"],
    schoolBackgrounds: ["SMK Kreatif/Multimedia", "SMK Teknik", "IPA"],
    pathwayTags: ["PTS bagus di kota besar", "Diploma/vokasi", "PTN di Jawa"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["sketsa", "riset pengguna", "prototype", "material dasar"],
    nextSteps: ["Buat prototype sederhana", "Observasi masalah produk di sekitar", "Latih sketsa dan dokumentasi proses"],
    cautionNotes: ["Perlu nyaman menerima feedback dan mengulang desain berkali-kali."],
    aiProfile: creativeBuilder
  },
  {
    id: "manajemen",
    name: "Manajemen",
    cluster: "Bisnis",
    careerDirection: "Pengelolaan organisasi, operasi, pemasaran, SDM, dan kewirausahaan",
    relatedCareers: ["Management Trainee", "Operations Officer", "Entrepreneur", "HR Officer"],
    subjects: ["Ekonomi", "Matematika", "Bahasa", "Sosiologi"],
    interests: ["Berjualan/bisnis", "Mengorganisir acara", "Menulis/berbicara", "Membantu orang"],
    skills: ["Leadership", "Komunikasi", "Problem solving", "Public speaking", "Numerik/hitung-hitungan"],
    workStyles: ["Banyak bertemu orang", "Terstruktur dan detail", "Dinamis di lapangan"],
    problemAreas: ["Bisnis", "Keuangan", "Sosial"],
    schoolBackgrounds: ["IPS", "SMK Bisnis", "IPA", "Bahasa"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar", "Kuliah dekat rumah"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["dasar bisnis", "analisis pasar", "keuangan dasar", "leadership praktis"],
    nextSteps: ["Ikut organisasi atau proyek jualan", "Belajar laporan keuangan sederhana", "Latih negosiasi dan presentasi"],
    cautionNotes: ["Jurusan ini luas, jadi perlu memilih spesialisasi sejak kuliah."],
    aiProfile: businessBuilder
  },
  {
    id: "akuntansi",
    name: "Akuntansi",
    cluster: "Keuangan",
    careerDirection: "Pencatatan, audit, pajak, dan pelaporan keuangan",
    relatedCareers: ["Accountant", "Auditor", "Tax Associate", "Finance Officer"],
    subjects: ["Ekonomi", "Matematika", "Komputer/TIK"],
    interests: ["Menghitung/analisis data", "Berjualan/bisnis"],
    skills: ["Ketelitian", "Numerik/hitung-hitungan", "Logika", "Problem solving"],
    workStyles: ["Terstruktur dan detail", "Banyak analisis sendiri"],
    problemAreas: ["Keuangan", "Bisnis", "Hukum"],
    schoolBackgrounds: ["IPS", "SMK Bisnis", "IPA"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "Kuliah dekat rumah", "Diploma/vokasi"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["dasar jurnal", "spreadsheet", "pajak dasar", "ketelitian dokumen"],
    nextSteps: ["Latihan spreadsheet dan pembukuan sederhana", "Pelajari siklus akuntansi", "Cari info sertifikasi pajak atau akuntansi"],
    cautionNotes: ["Tugas rutin makin otomatis, jadi kemampuan analisis dan konsultasi perlu diperkuat."],
    aiProfile: aiProfile(
      "pencatatan rutin dapat otomatis, tetapi audit, kepatuhan, interpretasi, dan tanggung jawab profesional tetap dibutuhkan.",
      {
        humanInteraction: 54,
        creativity: 35,
        physicalPractical: 10,
        ethicalJudgment: 86,
        complexProblemSolving: 72,
        professionalAccountability: 90,
        aiAugmentationPotential: 88,
        industryGrowth: 72,
        nonRoutineWork: 58
      }
    )
  },
  {
    id: "keuangan",
    name: "Keuangan dan Perbankan",
    cluster: "Keuangan",
    careerDirection: "Analisis keuangan, investasi, perbankan, dan perencanaan finansial",
    relatedCareers: ["Financial Analyst", "Bank Officer", "Investment Analyst", "Financial Planner"],
    subjects: ["Ekonomi", "Matematika", "Komputer/TIK"],
    interests: ["Menghitung/analisis data", "Berjualan/bisnis"],
    skills: ["Numerik/hitung-hitungan", "Ketelitian", "Komunikasi", "Problem solving"],
    workStyles: ["Terstruktur dan detail", "Banyak analisis sendiri", "Banyak bertemu orang"],
    problemAreas: ["Keuangan", "Bisnis"],
    schoolBackgrounds: ["IPS", "SMK Bisnis", "IPA"],
    pathwayTags: ["PTN di Jawa", "PTS bagus di kota besar", "Diploma/vokasi"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["financial literacy", "spreadsheet", "analisis risiko", "komunikasi klien"],
    nextSteps: ["Ikuti simulasi investasi edukatif", "Pelajari laporan keuangan", "Latih spreadsheet dan presentasi angka"],
    cautionNotes: ["Butuh integritas tinggi karena berkaitan dengan uang dan kepercayaan."],
    aiProfile: businessBuilder
  },
  {
    id: "aktuaria",
    name: "Aktuaria",
    cluster: "Matematika & Risiko",
    careerDirection: "Perhitungan risiko, asuransi, keuangan, dan pemodelan statistik",
    relatedCareers: ["Actuary", "Risk Analyst", "Insurance Analyst", "Quantitative Analyst"],
    subjects: ["Matematika", "Ekonomi", "Komputer/TIK"],
    interests: ["Menghitung/analisis data", "Coding/teknologi"],
    skills: ["Numerik/hitung-hitungan", "Logika", "Ketelitian", "Problem solving"],
    workStyles: ["Banyak analisis sendiri", "Terstruktur dan detail"],
    problemAreas: ["Keuangan", "Bisnis", "Teknologi"],
    schoolBackgrounds: ["IPA", "IPS"],
    pathwayTags: ["PTN di Jawa", "PTS bagus di kota besar"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["statistika lanjut", "probabilitas", "pemrograman data", "ujian profesi"],
    nextSteps: ["Perkuat matematika dan probabilitas", "Coba pemodelan risiko sederhana", "Cari tahu sertifikasi aktuaria"],
    cautionNotes: ["Jalur ini menantang secara matematika dan biasanya butuh sertifikasi profesi."],
    aiProfile: dataBuilder
  },
  {
    id: "statistika",
    name: "Statistika",
    cluster: "Data & Matematika",
    careerDirection: "Riset data, survei, eksperimen, dan pemodelan statistik",
    relatedCareers: ["Statistician", "Data Analyst", "Survey Researcher", "Research Analyst"],
    subjects: ["Matematika", "Komputer/TIK", "Ekonomi"],
    interests: ["Menghitung/analisis data", "Eksperimen/lab", "Coding/teknologi"],
    skills: ["Numerik/hitung-hitungan", "Ketelitian", "Logika", "Problem solving"],
    workStyles: ["Banyak analisis sendiri", "Terstruktur dan detail"],
    problemAreas: ["Teknologi", "Kesehatan", "Bisnis", "Pendidikan", "Lingkungan"],
    schoolBackgrounds: ["IPA", "IPS"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["statistika dasar", "pemrograman data", "metode survei", "visualisasi data"],
    nextSteps: ["Latihan membaca grafik", "Analisis dataset sederhana", "Pelajari spreadsheet, R, atau Python"],
    cautionNotes: ["Perlu sabar dengan konsep abstrak dan detail angka."],
    aiProfile: dataBuilder
  },
  {
    id: "farmasi",
    name: "Farmasi",
    cluster: "Kesehatan & Sains",
    careerDirection: "Obat, pelayanan farmasi, riset formula, dan keamanan penggunaan obat",
    relatedCareers: ["Pharmacist", "Clinical Pharmacy Assistant", "Regulatory Officer", "R&D Staff"],
    subjects: ["Kimia", "Biologi", "Matematika"],
    interests: ["Eksperimen/lab", "Membantu orang", "Menghitung/analisis data"],
    skills: ["Ketelitian", "Problem solving", "Kerja praktik", "Empati"],
    workStyles: ["Terstruktur dan detail", "Praktik langsung", "Banyak bertemu orang"],
    problemAreas: ["Kesehatan", "Teknologi"],
    schoolBackgrounds: ["IPA", "SMK Kesehatan"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar"],
    flexible: false,
    applied: true,
    expensive: true,
    competitive: true,
    skillGaps: ["kimia dasar", "biologi manusia", "ketelitian formula", "etika pelayanan"],
    nextSteps: ["Perkuat kimia dan biologi", "Cari info biaya dan beasiswa", "Kunjungi apotek atau lab sekolah jika memungkinkan"],
    cautionNotes: ["Biaya dan beban akademik bisa tinggi; siapkan opsi beasiswa atau kampus alternatif."],
    aiProfile: healthBuilder
  },
  {
    id: "teknologi-pangan",
    name: "Teknologi Pangan",
    cluster: "Sains Terapan",
    careerDirection: "Pengolahan pangan, keamanan makanan, riset produk, dan kualitas industri",
    relatedCareers: ["Food Technologist", "Quality Control", "Product Developer", "Food Safety Officer"],
    subjects: ["Kimia", "Biologi", "Matematika"],
    interests: ["Eksperimen/lab", "Kerja lapangan", "Menghitung/analisis data"],
    skills: ["Ketelitian", "Problem solving", "Kerja praktik", "Numerik/hitung-hitungan"],
    workStyles: ["Praktik langsung", "Terstruktur dan detail"],
    problemAreas: ["Kesehatan", "Bisnis", "Lingkungan"],
    schoolBackgrounds: ["IPA", "SMK Kesehatan", "SMK Bisnis"],
    pathwayTags: ["PTN luar Jawa", "PTN di Jawa", "Diploma/vokasi"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["kimia pangan", "mikrobiologi dasar", "quality control", "praktik lab"],
    nextSteps: ["Pelajari label nutrisi makanan", "Coba proyek eksperimen pangan aman", "Cari info industri pangan lokal"],
    cautionNotes: ["Banyak pekerjaan membutuhkan standar keamanan dan ketelitian tinggi."],
    aiProfile: engineeringBuilder
  },
  {
    id: "bioteknologi",
    name: "Bioteknologi",
    cluster: "Sains & Riset",
    careerDirection: "Riset biologis, teknologi kesehatan, pangan, dan lingkungan",
    relatedCareers: ["Lab Research Assistant", "Biotech Analyst", "Quality Analyst", "R&D Staff"],
    subjects: ["Biologi", "Kimia", "Matematika"],
    interests: ["Eksperimen/lab", "Menghitung/analisis data", "Membantu orang"],
    skills: ["Ketelitian", "Problem solving", "Logika", "Kerja praktik"],
    workStyles: ["Praktik langsung", "Banyak analisis sendiri", "Terstruktur dan detail"],
    problemAreas: ["Kesehatan", "Lingkungan", "Teknologi"],
    schoolBackgrounds: ["IPA", "SMK Kesehatan"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa"],
    flexible: false,
    applied: false,
    expensive: false,
    competitive: true,
    skillGaps: ["biologi sel", "kimia dasar", "praktik lab", "membaca jurnal sederhana"],
    nextSteps: ["Perkuat biologi dan kimia", "Ikut klub sains atau lomba riset", "Pelajari keselamatan lab"],
    cautionNotes: ["Sebagian jalur riset membutuhkan pendidikan lanjutan."],
    aiProfile: engineeringBuilder
  },
  {
    id: "kedokteran",
    name: "Kedokteran",
    cluster: "Kesehatan",
    careerDirection: "Diagnosis, perawatan pasien, dan tanggung jawab klinis profesional",
    relatedCareers: ["Dokter Umum", "Dokter Spesialis", "Medical Researcher", "Health Educator"],
    subjects: ["Biologi", "Kimia", "Fisika", "Matematika"],
    interests: ["Membantu orang", "Eksperimen/lab"],
    skills: ["Empati", "Ketelitian", "Problem solving", "Komunikasi", "Kerja praktik"],
    workStyles: ["Praktik langsung", "Banyak bertemu orang", "Terstruktur dan detail"],
    problemAreas: ["Kesehatan", "Sosial"],
    schoolBackgrounds: ["IPA", "SMK Kesehatan"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar"],
    flexible: false,
    applied: true,
    expensive: true,
    competitive: true,
    skillGaps: ["biologi manusia", "kimia", "ketahanan belajar", "komunikasi pasien"],
    nextSteps: ["Diskusi dengan dokter atau mahasiswa kedokteran", "Petakan biaya dan beasiswa", "Perkuat sains dan kebiasaan belajar"],
    cautionNotes: ["Biaya, durasi studi, dan persaingan masuk sangat tinggi; siapkan rencana cadangan kesehatan."],
    aiProfile: healthBuilder
  },
  {
    id: "gizi",
    name: "Gizi",
    cluster: "Kesehatan",
    careerDirection: "Nutrisi, edukasi pola makan, dan program kesehatan individu atau masyarakat",
    relatedCareers: ["Nutritionist", "Dietitian Assistant", "Food Program Officer", "Health Educator"],
    subjects: ["Biologi", "Kimia", "Bahasa"],
    interests: ["Membantu orang", "Eksperimen/lab", "Menulis/berbicara"],
    skills: ["Empati", "Komunikasi", "Ketelitian", "Problem solving"],
    workStyles: ["Banyak bertemu orang", "Terstruktur dan detail", "Praktik langsung"],
    problemAreas: ["Kesehatan", "Pendidikan", "Sosial"],
    schoolBackgrounds: ["IPA", "SMK Kesehatan"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "Kuliah dekat rumah"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["dasar nutrisi", "komunikasi edukasi", "biokimia dasar", "analisis menu"],
    nextSteps: ["Pelajari piring makan seimbang", "Coba membuat edukasi gizi sederhana", "Cari pengalaman kampanye kesehatan"],
    cautionNotes: ["Perlu kemampuan edukasi yang tidak menghakimi dan berbasis data."],
    aiProfile: healthBuilder
  },
  {
    id: "teknik-mesin",
    name: "Teknik Mesin",
    cluster: "Teknik",
    careerDirection: "Perancangan, produksi, energi, manufaktur, dan pemeliharaan mesin",
    relatedCareers: ["Mechanical Engineer", "Maintenance Engineer", "Manufacturing Engineer", "Energy Engineer"],
    subjects: ["Fisika", "Matematika", "Komputer/TIK"],
    interests: ["Memperbaiki barang/mesin", "Kerja lapangan", "Menghitung/analisis data"],
    skills: ["Problem solving", "Logika", "Kerja praktik", "Ketelitian", "Numerik/hitung-hitungan"],
    workStyles: ["Praktik langsung", "Dinamis di lapangan", "Terstruktur dan detail"],
    problemAreas: ["Infrastruktur", "Teknologi", "Lingkungan"],
    schoolBackgrounds: ["IPA", "SMK Teknik"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "Diploma/vokasi"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["fisika mekanika", "gambar teknik", "CAD dasar", "keselamatan kerja"],
    nextSteps: ["Perkuat fisika dan matematika", "Coba desain CAD sederhana", "Cari info magang bengkel atau manufaktur"],
    cautionNotes: ["Beberapa pekerjaan lapangan membutuhkan kesiapan fisik dan disiplin keselamatan."],
    aiProfile: engineeringBuilder
  },
  {
    id: "teknik-elektro",
    name: "Teknik Elektro",
    cluster: "Teknik",
    careerDirection: "Sistem listrik, elektronika, otomasi, telekomunikasi, dan energi",
    relatedCareers: ["Electrical Engineer", "Automation Engineer", "IoT Engineer", "Power System Engineer"],
    subjects: ["Fisika", "Matematika", "Komputer/TIK"],
    interests: ["Memperbaiki barang/mesin", "Coding/teknologi", "Eksperimen/lab"],
    skills: ["Logika", "Problem solving", "Teknologi", "Ketelitian", "Kerja praktik"],
    workStyles: ["Praktik langsung", "Terstruktur dan detail", "Banyak analisis sendiri"],
    problemAreas: ["Teknologi", "Infrastruktur", "Lingkungan"],
    schoolBackgrounds: ["IPA", "SMK Teknik"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "Diploma/vokasi"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["rangkaian listrik", "matematika teknik", "mikrokontroler", "keselamatan kerja"],
    nextSteps: ["Coba proyek elektronika kecil", "Pelajari listrik dasar secara aman", "Latih matematika dan fisika"],
    cautionNotes: ["Butuh ketelitian tinggi karena berkaitan dengan keselamatan sistem."],
    aiProfile: engineeringBuilder
  },
  {
    id: "teknik-sipil",
    name: "Teknik Sipil",
    cluster: "Teknik & Infrastruktur",
    careerDirection: "Perencanaan, konstruksi, transportasi, air, dan infrastruktur publik",
    relatedCareers: ["Civil Engineer", "Site Engineer", "Structural Engineer", "Construction Planner"],
    subjects: ["Fisika", "Matematika", "Komputer/TIK"],
    interests: ["Kerja lapangan", "Memperbaiki barang/mesin", "Menghitung/analisis data"],
    skills: ["Problem solving", "Ketelitian", "Numerik/hitung-hitungan", "Kerja praktik", "Leadership"],
    workStyles: ["Dinamis di lapangan", "Terstruktur dan detail", "Praktik langsung"],
    problemAreas: ["Infrastruktur", "Lingkungan", "Sosial"],
    schoolBackgrounds: ["IPA", "SMK Teknik"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "Diploma/vokasi"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["mekanika struktur", "gambar teknik", "manajemen proyek", "survey lapangan"],
    nextSteps: ["Amati proyek bangunan sekitar", "Pelajari gambar teknik dasar", "Latih fisika dan matematika"],
    cautionNotes: ["Pekerjaan bisa banyak di lapangan dan membutuhkan tanggung jawab keselamatan publik."],
    aiProfile: engineeringBuilder
  },
  {
    id: "teknik-industri",
    name: "Teknik Industri",
    cluster: "Teknik & Bisnis",
    careerDirection: "Optimasi proses, supply chain, quality control, dan manajemen operasi",
    relatedCareers: ["Industrial Engineer", "Supply Chain Analyst", "Process Improvement Specialist", "Quality Engineer"],
    subjects: ["Matematika", "Fisika", "Ekonomi", "Komputer/TIK"],
    interests: ["Menghitung/analisis data", "Mengorganisir acara", "Berjualan/bisnis", "Kerja lapangan"],
    skills: ["Problem solving", "Logika", "Leadership", "Ketelitian", "Komunikasi"],
    workStyles: ["Terstruktur dan detail", "Banyak bertemu orang", "Dinamis di lapangan"],
    problemAreas: ["Bisnis", "Teknologi", "Infrastruktur", "Keuangan"],
    schoolBackgrounds: ["IPA", "SMK Teknik", "SMK Bisnis"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar"],
    flexible: true,
    applied: true,
    expensive: false,
    competitive: true,
    skillGaps: ["statistika", "proses bisnis", "quality control", "komunikasi lintas tim"],
    nextSteps: ["Pelajari alur produksi sederhana", "Latih spreadsheet dan diagram proses", "Ikut proyek organisasi sekolah"],
    cautionNotes: ["Cocok untuk yang mau belajar teknik sekaligus bisnis dan orang."],
    aiProfile: engineeringBuilder
  },
  {
    id: "vokasi-teknik",
    name: "Vokasi Teknik",
    cluster: "Vokasi & Industri",
    careerDirection: "Keahlian terapan untuk manufaktur, otomasi, perawatan, dan instalasi teknik",
    relatedCareers: ["Technician", "Automation Technician", "Maintenance Staff", "Field Engineer Assistant"],
    subjects: ["Fisika", "Komputer/TIK", "Matematika"],
    interests: ["Memperbaiki barang/mesin", "Kerja lapangan", "Praktik langsung", "Coding/teknologi"],
    skills: ["Kerja praktik", "Ketelitian", "Problem solving", "Teknologi"],
    workStyles: ["Praktik langsung", "Dinamis di lapangan", "Terstruktur dan detail"],
    problemAreas: ["Teknologi", "Infrastruktur"],
    schoolBackgrounds: ["SMK Teknik", "IPA"],
    pathwayTags: ["Diploma/vokasi", "Sertifikasi/bootcamp", "Kuliah dekat rumah"],
    flexible: false,
    applied: true,
    expensive: false,
    competitive: false,
    skillGaps: ["alat ukur", "keselamatan kerja", "troubleshooting", "sertifikasi teknis"],
    nextSteps: ["Cari program D3 atau politeknik", "Bangun pengalaman praktik", "Kejar sertifikasi industri dasar"],
    cautionNotes: ["Jalur ini kuat untuk cepat kerja jika portofolio praktik dan sertifikasi dibangun."],
    aiProfile: engineeringBuilder
  },
  {
    id: "hukum",
    name: "Ilmu Hukum",
    cluster: "Hukum & Kebijakan",
    careerDirection: "Advokasi, regulasi, kepatuhan, mediasi, dan kebijakan publik",
    relatedCareers: ["Legal Officer", "Advocate", "Compliance Officer", "Policy Analyst"],
    subjects: ["Bahasa", "Sosiologi", "Sejarah", "Ekonomi"],
    interests: ["Menulis/berbicara", "Membantu orang", "Mengorganisir acara"],
    skills: ["Komunikasi", "Public speaking", "Ketelitian", "Problem solving", "Bahasa asing"],
    workStyles: ["Banyak bertemu orang", "Terstruktur dan detail", "Banyak analisis sendiri"],
    problemAreas: ["Hukum", "Sosial", "Bisnis", "Keuangan"],
    schoolBackgrounds: ["IPS", "Bahasa", "IPA"],
    pathwayTags: ["PTN di Jawa", "PTN luar Jawa", "PTS bagus di kota besar"],
    flexible: true,
    applied: false,
    expensive: false,
    competitive: true,
    skillGaps: ["membaca dokumen panjang", "argumentasi tertulis", "public speaking", "etika profesi"],
    nextSteps: ["Latih membaca berita hukum", "Ikut debat atau forum diskusi", "Belajar menulis argumen terstruktur"],
    cautionNotes: ["Untuk praktik advokat atau profesi tertentu, perlu pendidikan dan sertifikasi lanjutan."],
    aiProfile: lawBuilder
  }
];

export const careers = majors.flatMap((major) =>
  major.relatedCareers.map((title, index) => ({
    id: `${major.id}-${index + 1}`,
    title,
    direction: major.careerDirection,
    cluster: major.cluster
  }))
);
